name: Build Android APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          npm install --force
          npm install @ionic/react ionicons @ionic/react-router --force

      - name: Build Web Project
        run: npm run build

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Android
        run: |
          # إضافة منصة أندرويد ومزامنة الكود المصلح
          npx cap add android || true
          npx cap sync android
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ERT-Professional-App
          path: android/app/build/outputs/apk/debug/app-debug.apk
